sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd src
      script:
        - python3 -m src.similarity_test
        - python3 -m src.data.embed_gen_test
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
