# before_install:
# - mkdir -p $HOME/bin
# - wget https://github.com/git-lfs/git-lfs/releases/download/v2.5.2/git-lfs-linux-amd64-v2.5.2.tar.gz
# - tar xvfz git-lfs-linux-amd64-v2.5.2.tar.gz
# - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
# - export PATH=$PATH:$HOME/bin/
before_script: git lfs pull
