sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd src
      script:
        - python3 -m unittest discover -s ./ -p '*_test.py'
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
