sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python:
        - 3.7 
        - 3.6
        - 3.5
      before_script:
        - cd api/machine_learning
      script:
        - python3 -m unittest discover -s ./ -p '*_test.py'
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
