matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd api/machine_learning
      script:
        - python3 -m unittest discover -s ./ -p '*_test.py'
before_script: git lfs pull
